### ISSUE TITLE
on_connect callback only called when restarting MQTT Broker

### ISSUE THREAD

**Issue by dreichen** [stlehmann/Flask-MQTT#73] opened 2020-05-15 11:24 UTC
I am debugging my flask application I just deployed on a raspberry pi zero wh. On my linux machine (notebook) everything works like a charm, however, on the raspberry pi I discovered that the MQTT client does not acknowledge that it connects to the mosquitto broker although the MQTT log states

```
    1589448206: New client connected from ::1 as 15ae66e3-7fc3-4739-a5f5-a0fe16e6ed28 (c1, k5, u'test').
    1589448230: New connection from ::1 on port 1883.
```

I just discovered that the flask app does acknowledge its connection when I do

`    sudo service mosquitto restart`

After investigating a bit, I found out that my on_connect callback is just not called:

```
    def subscribe_topics():
        for topic in packet_manager.packets.keys():
            mqtt.subscribe(topic)
        
    @mqtt.on_connect()
    def handle_connect(client, userdata, flags, rc):
        print(" * Connected to MQTT Broker successfully")
        subscribe_topics()
```

I am using the follwing MQTT settings

```
    MQTT_CLIENT_ID = "webserver" #seems to be deprecated btw
    MQTT_BROKER_URL = 'localhost'
    MQTT_BROKER_PORT = 1883
    MQTT_USERNAME = 'test'
    MQTT_PASSWORD = 'test'
    MQTT_KEEPALIVE = 60
    MQTT_TLS_ENABLED = False
```

The print + subscription is only executed after restarting the mosquitto service, so the callback on_connect is not called properly

Interesting:
When I run the broker on the raspberry pi and connect the MQTT Client on my notebook to the raspberry pi's IP, everything works without restarting mosquitto.

I also tried to do the subscription of the topics outside of on_connect and everything works.
```
    def subscribe_topics():
        for topic in packet_manager.packets.keys():
            mqtt.subscribe(topic)
        
    @mqtt.on_connect()
    def handle_connect(client, userdata, flags, rc):
        print(" * Connected to MQTT Broker successfully")

    subscribe_topics()
```

I am using newest version of flask_mqtt (1.1.1) and paho_mqtt (1.0.5)

**Comment by 1voud** [comment] 2020-06-05 08:36
It looks like I'm facing the same issue. I was using version 1.0.5 and the server ran very stable for over a year. Last week I wanted to dockerize the project and ran into this problem. The new build was using version 1.1.1 on python 3.8.3.
When I start the Flask server I can see it connects to mosquitto (from the mosquitto log) on Armbian, but then it stops and does not continue with the subscriptions. I tried upgrading mosquittto from the native Armbian (Ubuntu) to the latest mosquitto version from the docker hub but it did not help.
Running the Flask server on Armbian and on my Arch laptop give the same behaviour. 

When I saw the issue above I tried the restart of mosquitto and indeed my program continues to connect and subscribe after this restart.

Reverting to Flask-MQTT 1.0.5 makes the server behave as stable as before

**Comment by 1voud** [comment] 2020-06-06 06:26
Browsing the code I found the option: connect_async. When using the non-default connect_async=True the issue seems to disappear.

**Comment by stlehmann** [comment] 2020-06-08 19:12
@1voud thanks for investigating. I suspected it could be some issue with connect/connect_async. I made connect_async optional in  41ef2fe3f2390d77db17ed8c8810bb19b9b029eb because there were some issues with it before. As far as I can tell this seems to be an ARM-only issue?

**Comment by stlehmann** [comment] 2020-06-08 19:16
@dreichen could you give it a try and use connect_async in your setup and see if it works.

**Comment by ffleandro** [comment] 2020-06-11 15:49
I've confirmed this issue and `connect_async = True` seems to solve it.
Also may be related to `eventlet.monkey_patch()`.

**Comment by dreichen** [comment] 2020-08-10 13:44
@ffleandro I do not use `eventlet`, so it has to be a general bug.

**Comment by kim-acmehi** [comment] 2020-09-17 15:45
I am seeing a similar issue where on_connect() is not getting called in my Flask app.  The app has clearly connected to the broker but the on_connect() callback did not execute.  This used to work reliably but the complexity of my app has grown so something other interaction may be affecting the Flask-MQTT operation.  Simple test cases always work but not the full app.  I am using `eventlet `and `monkey_patch`.  Platform is Raspberry Pi running RaspiOS buster.

I will investigate this further and report back.

**Comment by kim-acmehi** [comment] 2020-09-17 19:15
My problem was fixed by using `connect_async=True`.  I get on_connect() call backs every time now.

**Comment by stlehmann** [comment] 2020-09-29 08:38
The reason might be the change to

**Closed by stlehmann** 2020-09-29 08:38 UTC
Labels: bug
