### ISSUE TITLE
flask-mqtt，Receive real-time information, start a few hours after the program died, help

### ISSUE THREAD

**Issue by lbhyxyz123** [stlehmann/Flask-MQTT#75] opened 2020-08-18 07:21 UTC
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\fuzhou\fuzhou_device\dingler_device\venv\lib\site-packages\paho\mqtt\client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "D:\fuzhou\fuzhou_device\dingler_device\venv\lib\site-packages\paho\mqtt\client.py", line 1801, in loop_forever
    self._reconnect_wait()
  File "D:\fuzhou\fuzhou_device\dingler_device\venv\lib\site-packages\paho\mqtt\client.py", line 3449, in _reconnect_wait
    time.sleep(min(remaining, 1))
  File "D:\fuzhou\fuzhou_device\dingler_device\venv\lib\site-packages\eventlet\greenthread.py", line 36, in sleep
    hub.switch()
  File "D:\fuzhou\fuzhou_device\dingler_device\venv\lib\site-packages\eventlet\hubs\hub.py", line 298, in switch
    return self.greenlet.switch()
eventlet.hubs.IOClosed: [Errno 10057] Operation on closed file

**Comment by stlehmann** [comment] 2020-08-18 18:24
Please be so kind to drop some lines describing the nature of the problem and provide a minimal example to help others reproduce your problem. I will close this issue due to the lack of these informations.

**Closed by stlehmann** 2020-08-18 18:24 UTC
