### ISSUE TITLE
Sometimes cannot subscribe to topic

### ISSUE THREAD

**Issue by Lukanite** [stlehmann/Flask-MQTT#56] opened 2019-08-15 15:10 UTC
Loading the example in Firefox, sometimes I get error messages in the server logs that show that an attempt to subscribe was unsuccessful:
```
[2019-08-15 15:02:16,127] ERROR in __init__: Error 4 subscribing to topic: test
[2019-08-15 15:02:20,589] DEBUG in __init__: Subscribed to topic: test, qos: 1
[2019-08-15 15:02:27,596] DEBUG in __init__: Unsubscribed from topic: test
[2019-08-15 15:02:29,421] DEBUG in __init__: Subscribed to topic: test, qos: 1
[2019-08-15 15:02:30,597] DEBUG in __init__: Error 4 unsubscribing from topic: test
[2019-08-15 15:02:31,556] DEBUG in __init__: Subscribed to topic: test, qos: 1
[2019-08-15 15:02:32,642] DEBUG in __init__: Error 4 unsubscribing from topic: test
[2019-08-15 15:02:34,147] DEBUG in __init__: Subscribed to topic: test, qos: 1
[2019-08-15 15:02:35,159] DEBUG in __init__: Error 4 unsubscribing from topic: test
```

I thought that this might be a networking issue, so I set up a mosquitto server on the same one as the webserver and changed the broker url to point to it, but even then I'm still getting the same messages. Thoughts? I'm just hitting the subscribe/unsubscribe button a few times.

**Comment by Lukanite** [comment] 2019-08-15 15:12
Package versions:
```
asn1crypto (0.24.0)
attrs (17.4.0)
Automat (0.6.0)
blinker (1.4)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
cloud-init (19.1)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
distro-info (0.18ubuntu0.18.04.1)
dnspython (1.16.0)
dominate (2.4.0)
eventlet (0.25.0)
Flask (1.1.1)
Flask-Bootstrap (3.3.7.1)
Flask-MQTT (1.0.5)
Flask-SocketIO (4.2.1)
greenlet (0.4.15)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.6)
incremental (16.10.1)
itsdangerous (1.1.0)
Jinja2 (2.10.1)
jsonpatch (1.16)
jsonpointer (1.10)
jsonschema (2.6.0)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
MarkupSafe (1.0)
monotonic (1.5)
netifaces (0.10.4)
oauthlib (2.0.6)
paho-mqtt (1.4.0)
PAM (0.4.2)
pip (9.0.1)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycrypto (2.6.1)
pygobject (3.26.1)
PyJWT (1.5.3)
pyOpenSSL (17.5.0)
pyserial (3.4)
python-apt (1.6.4)
python-debian (0.1.32)
python-engineio (3.9.3)
python-socketio (4.3.1)
pyxdg (0.25)
PyYAML (3.12)
requests (2.18.4)
requests-unixsocket (0.1.5)
SecretStorage (2.3.1)
service-identity (16.0.0)
setuptools (39.0.1)
six (1.11.0)
ssh-import-id (5.7)
systemd-python (234)
Twisted (17.9.0)
typing (3.7.4)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.22)
visitor (0.1.3)
WALinuxAgent (2.2.40)
Werkzeug (0.15.5)
wheel (0.30.0)
zope.interface (4.3.2)
```

**Comment by stlehmann** [comment] 2020-04-28 10:22
Is this still an issue? As the issue is quite old I will close it. If it is still a problem feel free to answer and I will gladly reopen it.

**Closed by stlehmann** 2020-04-28 10:22 UTC
